#!/bin/sh
set -eu

## Script will be run as chrony user !
## GPS-enabled variant: generates chrony.conf (including refclock lines for
## gpsd's SHM segments), then hands off to s6 which supervises chronyd and
## gpsd as siblings. See Dockerfile.gps + assets/s6/services/.

DEFAULT_NTP="0.pool.ntp.org,1.pool.ntp.org,2.pool.ntp.org,3.pool.ntp.org"
CHRONY_CONF_FILE="/etc/chrony/chrony.conf"

CURRENT_USER="$(id -u)"
CURRENT_GROUP="$(id -g)"
CURRENT_USERGROUP="$CURRENT_USER:$CURRENT_GROUP"
CHRONY_USERGROUP="$(id -u chrony):$(id -g chrony)"

echo "
-------------------------------------
ℹ️ Container Information (GPS variant)
-------------------------------------
OS:            $(. /etc/os-release; echo "${PRETTY_NAME}")
Docker user:   $(whoami)
Docker uid:    $CURRENT_USER
Docker gid:    $CURRENT_GROUP
"

if [ "$CURRENT_USERGROUP" != "$CHRONY_USERGROUP" ]; then
  echo "[WARNING] Container running under a different user than recommended!"
  echo ""
fi

# Check if existing volumes/folders are writable
if [ ! -w "/etc/chrony" ] || [ ! -w "/run/chrony" ] || [ ! -w "/var/lib/chrony" ]; then
  echo "
It seems that the necessary folders are not writable by the container user ($CURRENT_USERGROUP).
As this container is running as non-root, it cannot fix the permissions it self.

Please remove the volumes or update them to be writable by $CURRENT_USERGROUP.
Or run the container with 'user: \"0:0\"' so it will ran as root so it can fix itself.

If using tmpfs update the config to:
tmpfs:
  - /etc/chrony:rw,mode=1750,uid=$CURRENT_USER,gid=$CURRENT_GROUP
  - /run/chrony:rw,mode=1750,uid=$CURRENT_USER,gid=$CURRENT_GROUP
  - /var/lib/chrony:rw,mode=1750,uid=$CURRENT_USER,gid=$CURRENT_GROUP
"
  exit 1
fi

# GPS_DEVICE is required in the GPS-enabled image — this is the whole reason
# to run the -gps variant. If you don't want gpsd, use the default image.
if [ -z "${GPS_DEVICE:-}" ]; then
  echo "[ERROR] GPS_DEVICE is required for the GPS-enabled image (e.g. /dev/ttyUSB0)."
  echo "        Use the default simonrupf/chronyd image if you don't need a GPS refclock."
  exit 1
fi

# confirm correct permissions on chrony run directory
if [ -d /run/chrony ]; then
  chown -R chrony:chrony /run/chrony
  chmod o-rx /run/chrony
  # remove previous pid file if it exist
  rm -f /var/run/chrony/chronyd.pid
fi

# confirm correct permissions on chrony variable state directory
if [ -d /var/lib/chrony ]; then
  chown -R chrony:chrony /var/lib/chrony
fi

## dynamically populate chrony config file.
{
  echo "# https://github.com/simonrupf/docker-chrony"
  echo
  echo "# chrony.conf file generated by startup script (GPS variant)"
  echo "# located at $0"
  echo
  echo "# time servers provided by NTP_SERVERS environment variables."
} > ${CHRONY_CONF_FILE}


# NTP_SERVERS environment variable is not present, so populate with default server
if [ -z "${NTP_SERVERS:-}" ]; then
  NTP_SERVERS="${DEFAULT_NTP}"
fi

# LOG_LEVEL environment variable is not present, so populate with chrony default (0)
# chrony log levels: 0 (informational), 1 (warning), 2 (non-fatal error) and 3 (fatal error)
if [ -z "${LOG_LEVEL:-}" ]; then
  LOG_LEVEL=0
else
  # confirm log level is between 0-3, since these are the only log levels supported
  if expr "${LOG_LEVEL}" : "[^0123]" > /dev/null; then
    # level outside of supported range, let's set to default (0)
    LOG_LEVEL=0
  fi
fi

IFS=","
for N in $NTP_SERVERS; do
  # strip any quotes found before or after ntp server
  N_CLEANED=$(printf "%s" "$N" | tr -d '"')

  # check if ntp server has a 127.0.0.0/8 address (RFC3330) indicating it's
  # the local system clock
  if echo "${N_CLEANED}" | grep -q '^127\.'; then
    echo "server ${N_CLEANED}" >> ${CHRONY_CONF_FILE}
    echo "local stratum 10"    >> ${CHRONY_CONF_FILE}

  # found external time servers
  else
    if [ "${ENABLE_NTS:-false}" = true ]; then
      echo "server ${N_CLEANED} iburst nts" >> ${CHRONY_CONF_FILE}
    else
      echo "server ${N_CLEANED} iburst" >> ${CHRONY_CONF_FILE}
    fi
  fi
done
unset IFS

# PTP0 configuration: if it has been passed through, it means we want to use it
if [ -e /dev/ptp0 ]; then
  echo "refclock PHC /dev/ptp0 poll 3 dpoll -2 stratum 2" >> ${CHRONY_CONF_FILE}
fi

# GPS refclock(s) — gpsd publishes samples on NTP SHM segments:
#   seg 0: NMEA / "second" identification (precision ~100ms)
#   seg 1: PPS (precision ~100ns, only if the receiver wires PPS through
#          and gpsd is configured to publish it)
# GPS_REFCLOCK_OFFSET compensates for serial-link latency.
GPS_REFCLOCK_OFFSET="${GPS_REFCLOCK_OFFSET:-0.0}"
echo "refclock SHM 0 refid GPS offset ${GPS_REFCLOCK_OFFSET} precision 1e-1" >> ${CHRONY_CONF_FILE}
if [ "${GPS_PPS:-false}" = true ]; then
  echo "refclock SHM 1 refid PPS precision 1e-7 prefer" >> ${CHRONY_CONF_FILE}
fi

# final bits for the config file
{
  echo
  echo "driftfile /var/lib/chrony/chrony.drift"
  echo "makestep 0.1 3"
  if [ -n "${NTP_DIRECTIVES}" ]; then
    echo -e "${NTP_DIRECTIVES}"
  fi
  if [ "${NOCLIENTLOG:-false}" = true ]; then
    echo "noclientlog"
  fi
  echo
  echo "allow all"
} >> ${CHRONY_CONF_FILE}

# enable control of system clock, disabled by default
SYSCLK="-x"
if [ "${ENABLE_SYSCLK:-false}" = true ]; then
  SYSCLK=""
fi

# Hand off to s6-svscan. The s6 run scripts read these env vars to know how
# to launch each daemon; exporting them puts them in the s6-supervise env.
export CHRONYD_ARGS="-U -u chrony -d ${SYSCLK} -L ${LOG_LEVEL}"
export GPSD_ARGS="-N -F /run/chrony/gpsd.sock -s ${GPS_BAUD:-9600} ${GPS_DEVICE}"

# Copy the service tree to /run/chrony (an already-writable volume/tmpfs)
# so s6 can write its supervise/ state without needing the rootfs to be
# writable. Using /run/chrony rather than /run keeps things consistent
# with the default image's volume declarations.
mkdir -p /run/chrony/services
cp -r /etc/s6/services/. /run/chrony/services/

exec /usr/bin/s6-svscan /run/chrony/services
