---
name: Deploy multi-architecture Docker images with buildx

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"
    tags:
      - "*"

permissions:
  contents: read

jobs:
  buildx:
    # This workflow is only of value for simonrupf/docker-chronyd repo and would always be skipped in forks
    if: github.repository == 'simonrupf/docker-chronyd'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false # Do not store the token or SSH key with the local git config
      - # we need qemu and buildx so we can build multiple platforms later
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
      - # BuildKit (used with `docker buildx`) is the best way to build images
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: simonrupf/chronyd
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            # used on a tag event
            type=ref,event=tag
      - name: Login to DockerHub
        if: success() && github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          platforms: linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x,linux/riscv64
          push: ${{ github.event_name != 'pull_request' && !contains(github.ref_name, 'dependabot') }}
